version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  open-pull-requests-limit: 10
  reviewers:
      - cclauss
      - cdrini
  schedule:
    interval: weekly
    day: sunday
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jquery
    versions:
    - "> 1.11.0"
  - dependency-name: jquery-migrate
    versions:
    - "> 1.2.1"
