##
## Production server config (wip)
## You probably want to run:
## docker-compose -f docker-compose.yml -f docker-compose.infogami-local.yml -f docker-compose.production.yml up -d
##

version: "3"
services:
  web:
    restart: always
    hostname: ${HOSTNAME:-$HOST}
    environment:
      - GUNICORN_OPTS= --workers 50 --timeout 300 --max-requests 500
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
      - PYENV_VERSION=3.8.6
    volumes:
      - ../olsystem:/olsystem
      - ../booklending_utils:/booklending_utils
  solr:
    environment:
      - SOLR_CONFIG=conf/solrconfig-prod.xml
      - HAPROXY=true
      - EXTRA_TOMCAT_JAVA_OPTS=-Xmx10g -Xms10g
