##
## Production server config (wip)
## You probably want to run:
## export COMPOSE_FILE="docker-compose.yml:docker-compose.production.yml"
## docker-compose up -d
##

version: "3.1"
services:
  web:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - GUNICORN_OPTS= --workers 50 --timeout 300 --max-requests 500
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
      - BEFORE_START=pip install -e /booklending_utils
    volumes:
      - ../booklending_utils:/booklending_utils
      - ../olsystem:/olsystem
      - ../olsystem/etc/ia.ini:/home/openlibrary/.config/ia.ini

  covers:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - GUNICORN_OPTS= --workers 30 --max-requests 500
      - COVERSTORE_CONFIG=/olsystem/etc/coverstore.yml
    volumes:
      - ../olsystem:/olsystem
      - /1:/1
  covers_nginx:
    image: nginx:1.19.4
    restart: always
    depends_on:
      - covers
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/covers_nginx.conf:/etc/nginx/sites-enabled/covers_nginx.conf:ro
      # Needed for HTTPS, since this is a public server
      - ../olsystem/etc/nginx/sites-available/default-docker.conf:/etc/nginx/sites-enabled/default:ro
      # Needs access to openlibrary for static files
      - ../olsystem:/olsystem
      - /1/var/lib/openlibrary/sitemaps/sitemaps:/sitemaps
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"
    secrets:
      - petabox_seed
      # Needed by default-docker.conf
      - ssl_certificate
      - ssl_certificate_key

  infobase:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - INFOBASE_OPTS= fastcgi
      - INFOBASE_CONFIG=/olsystem/etc/infobase.yml
    volumes:
      - ../olsystem:/olsystem
      - infobase-writelog:/1/var/lib/openlibrary/infobase/log
      - infobase-errorlog:/1/var/log/openlibrary/infobase-errors
  infobase_nginx:
    image: nginx:1.19.4
    restart: always
    depends_on:
      - infobase
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/infobase_nginx.conf:/etc/nginx/sites-enabled/infobase_nginx.conf:ro
      # Needs olsystem for black-listed IPs
      - ../olsystem:/olsystem
    ports:
      - 7000:7000
    networks:
      - webnet
    secrets:
      - petabox_seed

  affiliate-server:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - AFFILIATE_CONFIG=/openlibrary.yml
    image: oldev:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-affiliate-server-start.sh
    ports:
      - 31337:31337
    volumes:
      -  /opt/olsystem/etc/openlibrary.yml:/openlibrary.yml
    networks:
      - webnet
    logging:
      options:
        max-size: "512m"
        max-file: "4"
  solr-updater:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
    volumes:
      - ../olsystem:/olsystem
    logging:
      options:
        max-size: "512m"
        max-file: "4"

secrets:
    petabox_seed:
      file: /opt/.petabox/seed

    # SSL-related secrets
    ssl_certificate:
      file: /opt/.petabox/openlibrary.org.combined.crt
    ssl_certificate_key:
      file: /opt/.petabox/openlibrary.org.nopassword.key
volumes:
    infobase-writelog:
    infobase-errorlog:
