##
## Production server config (wip)
## You probably want to run:
## docker-compose -f docker-compose.yml -f docker-compose.infogami-local.yml -f docker-compose.production.yml up -d
##

version: "3.1"
services:
  web:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - GUNICORN_OPTS= --workers 50 --timeout 300 --max-requests 500
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
      - PYENV_VERSION=3.8.6
    volumes:
      - ../booklending_utils:/booklending_utils
      - ../olsystem:/olsystem
      - ../olsystem/etc/ia.ini:/openlibrary/.config/ia.ini

  covers:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - GUNICORN_OPTS= --workers 30 --max-requests 500
      - COVERSTORE_CONFIG=/olsystem/etc/coverstore.yml
      - PYENV_VERSION=3.8.6
    volumes:
      - ../olsystem:/olsystem
      - /1:/1
  covers_nginx:
    image: nginx:1.19.4
    restart: always
    depends_on:
      - covers
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/covers_nginx.conf:/etc/nginx/sites-enabled/covers_nginx.conf:ro
      # Needs access to openlibrary for static files
      - .:/openlibrary
      - ../olsystem:/olsystem
      - /1/var/lib/openlibrary/sitemaps/sitemaps:/sitemaps
    ports:
      - 8081:8081
    networks:
      - webnet
    secrets:
      - petabox_seed

  infobase:
    restart: always
    hostname: "$HOSTNAME"
    environment:
      - INFOBASE_OPTS= fastcgi
      - INFOBASE_CONFIG=/olsystem/etc/infobase.yml
      - PYENV_VERSION=3.8.6
    volumes:
      - ../olsystem:/olsystem
      -  /1:/1
  infobase_nginx:
    image: nginx:1.19.4
    restart: always
    depends_on:
      - infobase
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/infobase_nginx.conf:/etc/nginx/sites-enabled/infobase_nginx.conf:ro
      # Needs olsystem for black-listed IPs
      - ../olsystem:/olsystem
    ports:
      - 7000:7000
    networks:
      - webnet
    secrets:
      - petabox_seed

secrets:
   petabox_seed:
     file: /opt/.petabox/seed
