version: "3"
services:
  web:
    image: oldev:latest
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - OL_CONFIG=${OL_CONFIG:-/openlibrary/conf/openlibrary.yml}
      - GUNICORN_OPTS=${GUNICORN_OPTS:- --reload --workers 4 --timeout 180}
      # Branch to pull infogami from. Leave blank to use production infogami for py2, master for py3
      # Set to "local" to not pull anything and use whatever you've got locally in vendor/infogami
      # ^ NOTE: Also need to uncomment the infogami volume mount (below) if doing this!
      - INFOGAMI=${INFOGAMI:-}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-web-start.sh
    ports:
      - 8080:80
      - 3000:3000
    depends_on:
      - db
      - infobase
    volumes:
      # Persistent volume mount for installed git submodules
      - ol-vendor:/openlibrary/vendor
      # Persistent volume mount for generated css and js
      - ol-build:/openlibrary/static/build
      # Persistent volume mount for node_modules
      - ol-nodemodules:/openlibrary/node_modules
      # Persistent volume mount for Internet Archive access
      - /olsystem/etc/ia.ini:/openlibrary/.config/ia.ini
      # The above volume mounts are required so that the local dev bind mount below
      # does not clobber the data generated inside the image / container
      - .:/openlibrary
    networks:
      - webnet
      - dbnet
  solr:
    image: olsolr:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.olsolr
    restart: always
    environment:
      - ENV=${ENV:-dev}
    ports:
      - 8983:8983
    volumes:
      - solr-data:/var/lib/solr/data
    networks:
      - webnet
  memcached:
    image: memcached
    networks:
      - webnet
  db:
    image: postgres:9.3
    networks:
      - dbnet
    volumes:
      - .:/openlibrary
      # Any files inside /docker-entrypoint-initdb.d/ will get run by postgres
      # if the db is empty (which as of now is always, since we don't store the
      # postgres data anywhere).
      - ./docker/ol-db-init.sh:/docker-entrypoint-initdb.d/ol-db-init.sh
  covers:
    image: oldev:latest
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - INFOGAMI=${INFOGAMI:-}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-covers-start.sh
    ports:
      - 8081:8081
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
    networks:
      - webnet
      - dbnet
  infobase:
    image: oldev:latest
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - INFOGAMI=${INFOGAMI:-}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-infobase-start.sh
    ports:
      - 7000:7000
    depends_on:
      - db
    volumes:
      - ol-vendor:/openlibrary/vendor
      - .:/openlibrary
    networks:
      - webnet
      - dbnet
  home:
    image: oldev:latest
    environment:
      - PYENV_VERSION=${PYENV_VERSION:-}
      - INFOGAMI=${INFOGAMI:-}
    build:
      context: .
      dockerfile: docker/Dockerfile.oldev
    command: docker/ol-home-start.sh
    volumes:
      - ol-vendor:/openlibrary/vendor
      - ol-build:/openlibrary/static/build
      - ol-nodemodules:/openlibrary/node_modules
      - .:/openlibrary
    networks:
      - webnet
      - dbnet
networks:
  webnet:
  dbnet:
volumes:
  solr-data:
  ol-vendor:
  ol-build:
  ol-nodemodules:
