# This file is applied "on top" of docker-compose.yml when docker-compose
# is used without the -f parameter. It contains local development specific
# configuration options which we don't want to apply to production/staging

version: "3.1"
services:
  covers:
    ports:
      - 7075:7075
