name: Label inactive issues and pull requests
on:
  schedule:
    - cron: "12 2 * * *"

jobs:
  label-stale:
    if: github.repository_owner == 'internetarchive'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          start-date: 2025-01-01
          exempt-issue-labels: 'no-automation,"Type: Epic"'
          exempt-assignees: jimchamp,mekarpeles,cdrini,scottbarnes,raybb,seabelis,hornc
          days-before-close: -1  # signifies that neither issues nor pull requests are to be closed
          days-before-issue-stale: 14
          days-before-pr-stale: -1
          include-only-assigned: true
          stale-issue-label: "Needs: Review Assignee"
          stale-issue-message: ""
          repo-token: ${{ secrets.GITHUB_TOKEN }}
